modLoader = "javafml"
loaderVersion = "[5,)"
license = "MIT"
issueTrackerURL = "https://github.com/kulisaiji/teasememe/issues"

[[mods]]
modId = "teasememe"
version = "${version}"
displayName = "TeaseMeme"
authors = "kulisaiji"
description = '''
A multi-platform Minecraft mod with custom entities and features.
'''

[[mixins]]
config = "teasememe.mixins.json"

[[dependencies.teasememe]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.teasememe]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.teasememe]]
modId = "architectury"
type = "required"
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.teasememe]]
modId = "geckolib"
type = "required"
versionRange = "[4.7.0,)"
ordering = "AFTER"
side = "BOTH"
